---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(targets)
library(tidyverse)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Result: basic stats table

```{r}
tar_read(table_descriptive_stats) %>%
  knitr::kable(
    caption = "The mean and standard deviation of metabolites in the lipidomics dataset."
  )
```

## Results: Distribution plot

```{r}
tar_read(plot_distributions)
```

## Model results from logistic regression

## Running multiple models

```{r}
just_cholesterol <- lipidomics %>%
  filter(metabolite == "Cholesterol") %>%
  preprocess()

lipidomics %>%
  filter(metabolite == "Cholesterol") %>%
  preprocess() %>%
  fit_all_models()
```

## Figure of model estimates

```{r}
tar_read(plot_model_results)
```

## Appendix

```{r}
tar_read(model_results) %>%
  knitr::kable(
    caption = "Model output from logistic regression"
  )
```
